language: go
go:
  - tip
before_install:
  - sudo apt-get update -qq > apt-get.out 2>&1  || (cat apt-get.out && exit 1)
  - sudo apt-get install bzr mercurial git -qq > apt-get.out 2>&1 || (cat apt-get.out && exit 1)
notifications:
  email:
    recipients:
      - piyush@piyushverma.net
    on_success: change
    on_failure: always
