language: go

go:
  - tip

before_install:
  - go get launchpad.net/goamz/s3
  - go get github.com/HouzuoGuo/tiedot
  - go get gopkg.in/yaml.v2

script:
  - go build -v ./...

notifications:
  slack: siminars:st82ura5uv0xQ52hTmHCqiNs
  email:
    recipients:
      - piyush@piyushverma.net
    on_success: change
    on_failure: always
